fromgron:
	python ./load_gron.py --input-name "streamlit1" --input-path=~/experiments/meta-meme/llms/llama2-7b-chat-codeCherryPop-qLoRA-GPTQ/streamlit.md
#b

fromgit:
	python ./load_dir.py --input-path=~/experiments/streamlit-hackathon/data

orake :
	python rake.py 2>&1 | tee ../../../../test/output/workflow_output1.json 

test:
	python step1.py
