name: ci

on:
  push:

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        # -
        # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        #   name: Set up QEMU
        #   uses: docker/setup-qemu-action@v3
     
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker buildx create --use
          docker buildx inspect default --bootstrap
          docker buildx build --tag myapp:latest .
          
      - name: Run tests
        run: docker-compose up --abort-on-container-exit
    
# To use the `docker/setup-buildx-action` with GitHub Actions to build and test your Dockerized application, follow these steps:

# 1. **Set Up Your Dockerized Application:**
#    Ensure your application is Dockerized and includes a Dockerfile.

# 2. **Create a Docker Compose File (Optional):**
#    If needed, create a `docker-compose.yml` file to define your application's services and dependencies.

# 3. **Configure GitHub Repository:**
#    Create a GitHub repository for your project if you haven't already. Push your Dockerized application code, including the Dockerfile and docker-compose file (if used), into this repository.

# 4. **Create a GitHub Actions Workflow:**
#    Create a `.github/workflows/docker.yml` file for your GitHub Actions workflow. This workflow will utilize `docker/setup-buildx-action` to build and test your Dockerized application.

# 5. **Testing Locally:**
#    To test your Dockerized application locally:

#    - Install Docker on your local machine.
#    - Clone your GitHub repository.
#    - Navigate to the project directory and run `docker-compose up` to start your application's containers.
#    - Access your application at `http://localhost` (or the appropriate URL) in your web browser.

# 6. **Customize as Needed:**
#    Customize the workflow, Dockerfile, and docker-compose file according to your specific project requirements.

# Make sure to replace `<base_image>` with the actual base image you want to use in your Dockerfile. This example incorporates the `docker/setup-buildx-action` for improved Docker building capabilities within GitHub Actions.b
